/**
 * Represents an advanced AI opponent ("Medium" difficulty) that utilizes strategic evaluation.
 * It builds a threat map to avoid dangerous tiles, prioritizes capturing valuable structures (HQ, Factories),
 * and dynamically purchases counter-units based on the enemy's army composition.
 *
 * @author xpruzir00
 * @author xblizna00
 * (Note: The initial structure of this bot was generated by AI, as documented in audit_ai.md)
 */

package gamer;

import java.util.*;
import board.GameBoard;
import board.Position;
import board.Terrain;
import board.Tile;
import game.PathFinder;
import game.Session;
import unit.Unit;
import unit.UnitType;

public class GeminiBot {
    private final PathFinder pathFinder;
    private final Random random = new Random();

    // State trackers to allow step-by-step turns
    private Iterator<Unit> unitIterator;
    private Iterator<Tile> factoryIterator;
    private boolean isTurnActive = false;

    // Cache for the threat map
    private Set<Position> threatMap = new HashSet<>();

    public GeminiBot(PathFinder pathFinder) {
        this.pathFinder = pathFinder;
    }

    // Generate a threat map at the start of each turn.
    // We calculate the movement reach and attack range of all enemy units 
    // to identify dangerous tiles and avoid unnecessary casualties.
    private void startTurn(Session session) {
        Player me = session.getActive();
        GameBoard board = session.getGameBoard();

        // Take a snapshot of units and factories at the beginning of the turn
        unitIterator = new ArrayList<>(board.getUnitsOf(me)).iterator();
        factoryIterator = board.getTilesOf(me).stream()
                .filter(t -> t.getTerrain().isProduceUnits() && t.isEmpty())
                .toList()
                .iterator();

        // Calculate threat map safely at the start of the turn
        threatMap.clear();
        List<Unit> enemies = board.getAllUnits().stream()
                .filter(u -> u.getPlayer() != me && u.isAlive())
                .toList();

        for (Unit enemy : enemies) {
            // SAFETY CHECK: Skip units that cannot attack (like Transports) to prevent NullPointerException
            if (enemy.getType().getAttackRange() == null)
                continue;

            Map<Position, Integer> enemyReach = pathFinder.findReachableTiles(enemy);
            for (Position reachablePos : enemyReach.keySet()) {
                int attackRange = enemy.getType().getAttackRange().max();
                threatMap.addAll(getTilesInRange(reachablePos, attackRange, board));
            }
        }

        isTurnActive = true;
    }

    // Artillery rule enforcement: If the unit cannot move and attack in the same turn,
    // check if an enemy is already within range. If so, cancel movement (bestTarget = startPos)
    // to prioritize shooting over repositioning.
    public boolean performNextAction(Session session) {
        if (!isTurnActive) {
            startTurn(session);
        }

        Player me = session.getActive();
        GameBoard board = session.getGameBoard();
        List<Unit> enemies = board.getAllUnits().stream()
                .filter(u -> u.getPlayer() != me && u.isAlive())
                .toList();

        // PHASE 1: Move and attack with units
        if (unitIterator != null && unitIterator.hasNext()) {
            Unit unit = unitIterator.next();

            // Skip units that might have died since the turn started
            if (!unit.isAlive()) {
                return true;
            }

            Position startPos = unit.getPosition();
            Map<Position, Integer> reachableMoves = pathFinder.findReachableTiles(unit);
            Position bestTarget = startPos;
            boolean shouldStayToShoot = false;

            if (!unit.getType().isCanAttackAfterMove()) {
                for (Unit enemy : enemies) {
                    if (unit.canAttackTo(enemy)) {
                        shouldStayToShoot = true;
                        break;
                    }
                }
            }

            if (!shouldStayToShoot && !reachableMoves.isEmpty()) {
                bestTarget = getBestMove(unit, reachableMoves.keySet(), board, enemies, me);
            }

            boolean moved = !startPos.equals(bestTarget);

            // GUI RULE: Only move if target tile is completely empty, or we are staying still
            if (moved && board.getTile(bestTarget).isEmpty()) {
                session.moveUnit(unit, bestTarget);
            } else if (moved) {
                // If the tile got occupied (should be stopped by PathFinder, but just in case)
                bestTarget = startPos;
                moved = false;
            }

            Tile currentTile = board.getTile(unit.getPosition());

            // GUI RULE: Same conditions as GameController.canCapture()
            boolean canCapture = !unit.isCaptured()
                    && unit.getType().isCanCapture()
                    && currentTile.getTerrain().isCapturable()
                    && (currentTile.getOwner() == null || currentTile.getOwner() != me);

            // GUI RULE: Same conditions as GameController.canSelectedUnitAttackNow()
            boolean canAttackNow = !unit.isUsed()
                    && (unit.getType().isCanAttackAfterMove() || !moved);

            boolean didAction = false;
            if (canCapture) {
                session.tryCapture(unit, currentTile);
                didAction = true;
            } else if (canAttackNow) {
                Unit targetEnemy = getBestEnemyToAttack(unit, enemies);
                // GUI RULE: Ensure target is valid and in range
                if (targetEnemy != null && unit.canAttackTo(targetEnemy)) {
                    session.attack(unit, targetEnemy);
                    didAction = true;
                }
            }
            if (!didAction)
                unit.setUsed(true);
            return true; // We performed an action!
        }

        // PHASE 2: Buy units from factories
        if (factoryIterator != null && factoryIterator.hasNext()) {
            Tile t = factoryIterator.next();

            // Skip if the factory got occupied during the current turn
            if (!t.isEmpty()) {
                return true;
            }

            buySmartUnit(session, board.getPosition(t), me, enemies);
            return true; // We performed an action!
        }

        // PHASE 3: Everything is finished
        isTurnActive = false;
        return false;
    }

    private Position getBestMove(Unit unit, Set<Position> reachable, GameBoard board,
            List<Unit> enemies, Player me) {
        Position bestMove = unit.getPosition();
        int bestScore = Integer.MIN_VALUE;

        // Determine if we are in "early game" (greedy phase)
        boolean earlyGame = board.getUnitsOf(me).size() < 6;

        for (Position pos : reachable) {
            int score = evaluatePosition(unit, pos, board, enemies, me, earlyGame);
            if (score > bestScore) {
                bestScore = score;
                bestMove = pos;
            }
        }
        return bestMove;
    }
    //=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=//
    // --- BUILDING PRIORITIES (Economy & Win Condition) ---                               //
    // HQ grants +2000 score because capturing it results in an instant win.               //
    // Factories grant +800 as they provide a crucial spawning advantage.                  //
    // Cities grant +600 in the early game to quickly boost income, dropping to +300 later.//
    //                                                                                     //
    // --- SURVIVABILITY & TERRAIN ---                                                     //
    // Prefer tiles with a high defense bonus (e.g., Mountains, Forests).                  //
    // If the unit has low HP (<= 60) and is on an owned healing tile, stay and heal       //
    // (+200 score).                                                                       //
    //                                                                                     //
    // --- THREAT AVOIDANCE ---                                                            //
    // If the evaluated tile is within the enemy threat map, apply a penalty.              //
    // Infantry tries to avoid combat entirely (-300) unless capturing an HQ.              //
    // Injured units (< 50 HP) get a -200 penalty to retreat.                              //
    //=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=//
    private int evaluatePosition(Unit unit, Position pos, GameBoard board, List<Unit> enemies,
            Player me, boolean earlyGame) {
        int score = 0;
        Tile tile = board.getTile(pos);

        // 1. Capture Priority
        if (unit.getType().isCanCapture() && tile.getTerrain().isCapturable()
                && tile.getOwner() != me) {
            if (tile.getTerrain() == Terrain.HQ)
                score += 2000;
            else if (tile.getTerrain() == Terrain.FACTORY)
                score += 800;
            else if (tile.getTerrain() == Terrain.CITY)
                score += earlyGame ? 600 : 300;

            if (tile.getCaptureHp() < 20)
                score += 100;
        }

        // 2. Defense and Healing
        score += tile.getTerrain().getDefenseBonus() * 15;
        if (unit.getHp() <= 60 && tile.getTerrain().isHeals() && tile.getOwner() == me) {
            score += 200; // Prioritize resting if hurt
        }

        // 3. Threat Map Avoidance
        if (threatMap.contains(pos)) {
            // Penalize moving squishy units into danger unless capturing HQ
            if (unit.getType() == UnitType.INFANTRY && tile.getTerrain() != Terrain.HQ) {
                score -= 300;
            } else if (unit.getHp() < 50) {
                score -= 200; // Damaged units avoid danger
            }
        }

        // 4. Attack Positioning
        if (unit.getType().isCanAttackAfterMove()) {
            for (Unit enemy : enemies) {
                if (canAttackFromPosition(pos, unit, enemy)) {
                    int potentialDamage = unit.getType().getDamageAgainst(enemy.getType());
                    score += potentialDamage * 2; // Weight high damage moves
                    if (enemy.getHp() <= potentialDamage) {
                        score += 300; // Bonus for securing a kill
                    }
                }
            }
        } else {
            // For CANNON/Rockets, try to get just outside enemy movement range
            for (Unit enemy : enemies) {
                if (canAttackFromPosition(pos, unit, enemy)) {
                    score += 150; // Good position to shoot next turn
                    if (!threatMap.contains(pos)) {
                        score += 200; // Safe position to shoot next turn!
                    }
                }
            }
        }

        // Move towards the general direction of enemies or neutral cities if nothing else to do
        if (score < 100) {
            score -= closestTargetDistance(pos, board, enemies, unit.getType().isCanCapture(), me);
        }

        score += random.nextInt(10);
        return score;
    }

    private int closestTargetDistance(Position pos, GameBoard board, List<Unit> enemies,
            boolean canCapture, Player me) {
        int minDistance = Integer.MAX_VALUE;
        if (canCapture) {
            for (Tile t : board.getAllTiles()) {
                if (t.getTerrain().isCapturable() && t.getOwner() != me) {
                    minDistance = Math.min(minDistance, pos.distanceTo(board.getPosition(t)));
                }
            }
        } else {
            for (Unit enemy : enemies) {
                minDistance = Math.min(minDistance, pos.distanceTo(enemy.getPosition()));
            }
        }

        // SAFETY CHECK: Prevent integer underflow if no targets are found
        return minDistance == Integer.MAX_VALUE ? 0 : minDistance;
    }

    private Unit getBestEnemyToAttack(Unit attacker, List<Unit> enemies) {
        Unit bestTarget = null;
        int bestScore = -1;

        for (Unit enemy : enemies) {
            if (enemy.isAlive() && attacker.canAttackTo(enemy)) {
                int damage = attacker.getType().getDamageAgainst(enemy.getType());
                int score = damage;

                // Prioritize kills
                if (damage >= enemy.getHp()) {
                    score += 500;
                }
                // Prioritize expensive units
                score += enemy.getType().getCost() / 100;

                if (score > bestScore) {
                    bestScore = score;
                    bestTarget = enemy;
                }
            }
        }
        return bestTarget;
    }

    // Dynamic counter-unit purchasing based on enemy army composition:
    // If the enemy has many tanks (> 2), buy a TANK to hold the frontline.
    // If the enemy is swarming with infantry (> 3), buy a CANNON for AoE/ranged clearing.
    private void buySmartUnit(Session session, Position pos, Player me, List<Unit> enemies) {
        int money = me.getMoney();

        // Count enemy types
        long enemyInfantry = enemies.stream().filter(u -> u.getType() == UnitType.INFANTRY).count();
        long enemyTanks = enemies.stream()
                .filter(u -> u.getType() == UnitType.TANK || u.getType() == UnitType.CANNON)
                .count();

        UnitType toBuy = null;

        // Rock-Paper-Scissors buying logic
        if (money >= UnitType.TANK.getCost() && enemyTanks > 2) {
            toBuy = UnitType.TANK; // Counter heavy armor
        } else if (money >= UnitType.CANNON.getCost() && enemyInfantry > 3) {
            toBuy = UnitType.CANNON; // Good against swarms if protected
        } else if (money >= UnitType.TANK.getCost()) {
            toBuy = UnitType.TANK; // Solid default
        } else if (money >= UnitType.INFANTRY.getCost()) {
            toBuy = UnitType.INFANTRY; // Always buy something if possible
        }

        if (toBuy != null) {
            // GUI RULE: Same conditions as GameController.canBuyUnit()
            boolean canAfford = me.canAfford(toBuy.getCost());
            boolean isFactoryEmpty = session.getGameBoard().getTile(pos).isEmpty();

            if (canAfford && isFactoryEmpty) {
                session.buyUnit(pos, toBuy);
            }
        }
    }

    private boolean canAttackFromPosition(Position pos, Unit unit, Unit enemy) {
        if (enemy == null || !enemy.isAlive())
            return false;
        if (unit.getType().getAttackRange() == null)
            return false;
        int dist = pos.distanceTo(enemy.getPosition());
        return unit.getType().getAttackRange().canReach(dist);
    }

    // Helper to get all tiles within a specific range for the threat map
    private Set<Position> getTilesInRange(Position center, int range, GameBoard board) {
        Set<Position> tiles = new HashSet<>();
        for (int x = center.x() - range; x <= center.x() + range; x++) {
            for (int y = center.y() - range; y <= center.y() + range; y++) {
                Position p = new Position(x, y);
                if (board.isValidPosition(p) && center.distanceTo(p) <= range) {
                    tiles.add(p);
                }
            }
        }
        return tiles;
    }
}
